/// CommandVectors.mo: the recorded hash of every command family under every encoding version. Generated by
/// tools/record_command_vectors.sh; a hash that moves under a version that shipped is a build failure.
///
/// Attribution: Thebes Core Team. Licence: Apache 2.0.

import Freeze "mo:kernel/domain/Freeze";

module {
  public func vectors() : [Freeze.Vector] {
    [
      { family = "openBook"; version = 1; hex = "7325e59cc2e5da28b842d079c65a2c1eaedafb85fa5521b5fed9372509973c8a" },
      { family = "closeBook"; version = 1; hex = "1385d33090d01917905e92687916faa5692f85ff0829596c911d6091f4b603c0" },
      { family = "defineRole"; version = 1; hex = "b86e7237d16e2f9f477d8a325e7050ebb7339717e5fbbca1a5deab92b39bfb7c" },
      { family = "grantRole"; version = 1; hex = "31bba3d6e11a893ee6a1a9eda4df0a09f4a931e303c70c02fe6474ca7206c5dc" },
      { family = "revokeRole"; version = 1; hex = "cb56e0df7f8452b4d2eb3787ecffdf037e3782d3fa88532178c436633eeee658" },
      { family = "setDualPolicy"; version = 1; hex = "b71ac73184769f59fcff6682511d8c9edbfe124dc1aecdfffdfee7c8f5349f78" },
      { family = "clearDualPolicy"; version = 1; hex = "ba0d31b9461f1235e786a9ad79778986e27bbb0b68fcf6e965afd903563440e4" },
      { family = "setFeatureActivation"; version = 1; hex = "deba74bd8ed20c742ef0b67f2b299440fed09c9a5639723236a3b9a900fdb64f" },
      { family = "setDeskIdentity"; version = 1; hex = "f9a72a7c1aeaec358f33894b849243711be8edd750efb9a4a8d804ef2c1033d7" },
      { family = "journalRegisterCurrency"; version = 1; hex = "3f5d8d77c911b92256a520d8e31e3e6790259fdab1a769821e4db07e97490bbb" },
      { family = "journalOpenAccount"; version = 1; hex = "848e68cfd0eb27c249b6a390ee8f868869c2fc956a51a27b6e6611bfc61236b3" },
      { family = "journalCloseAccount"; version = 1; hex = "c50fee148e6e068b5d644c787c692a944a72219bd103c4f186e1e17c8fa09b65" },
      { family = "journalOpenPeriod"; version = 1; hex = "a2d8433643ba6b851b1612dc09ed83262e877d17023fe76267c0127c4b5d554e" },
      { family = "journalClosePeriod"; version = 1; hex = "a36c71e84ca7453228f7b1fc1fef72817c9e1203c2566df34a773534e28bc63a" },
      { family = "journalSetCalendar"; version = 1; hex = "ea33513329a4b4af927c6d12d97ddb7782ef99d6ed38cde7dc8621fb06695f89" },
      { family = "journalSetCalendarAuthority"; version = 1; hex = "408d2de2d6a82de70e320072a473bd3a5e6268df0d99a5c96dd6eb0abbf30c79" },
      { family = "journalRollBusinessDate"; version = 1; hex = "962210326d2e136e7d9b6a80df735bf8e5c07207316eac9e73e779f335ad2da4" },
      { family = "journalSetActivationHeight"; version = 1; hex = "b407f4798855291880ffeaf8a676164f0da53877b1bcadaf3e317444c9959b29" },
      { family = "setFunctionalCurrency"; version = 1; hex = "7114f9db9a4e8ae93eed226d546ee8069e45b8b21e5c5afec86bb14c579da79c" },
      { family = "setFxPair"; version = 1; hex = "221e629ded24b2d64d022f372fc575bf7488695a0a800023f8a144c9d64dc561" },
      { family = "setFxRate"; version = 1; hex = "475db0cfd5970c78dd7ae455ba8f245fac24b8ff893c99fc55e00c530d491221" },
      { family = "recordRateFixing"; version = 1; hex = "b4f8978d4e76654ef6767dd93dd77f17690fce2e7a26e7096770cbf33a91a20a" },
      { family = "openEndOfDay"; version = 1; hex = "15b5d5cfca8b44ecdd564fa620c1e0339594dfcfec3779ebf7adfce32b081598" },
      { family = "setRetryPolicy"; version = 1; hex = "c1e6a76813ff89c5ac97815dd67baffcb2719790a625f7b0a874416424c3c7c1" },
      { family = "resolveEndOfDayFailure"; version = 1; hex = "55a2639794d58873b06e977255f8321dfad62118dd88ae0e6672226626149556" },
      { family = "clearAlert"; version = 1; hex = "b2ae61c471cbee0532f568cbde523a6ef9e291d2b3cd3427e1679416bfac0d76" },
      { family = "setTreasuryPolicy"; version = 1; hex = "8b336363191a50e9af37fee3bdceb20103d9161506be77897c4cff822619190d" },
      { family = "registerSecurity"; version = 1; hex = "fa35a3c26c32e1f085a364b14c6849c3697459cac628f616b7d1b150f62fbbf5" },
      { family = "publishCurve"; version = 1; hex = "91bc22655dd5d57b0baca236bc97613798651073062ca249632b73443cc7f006" },
      { family = "setTreasuryLimit"; version = 1; hex = "7b6b0ca2d76297d54e8a7fd4553c2b1ccbee83da15fff27731e82d5d34220d8d" },
      { family = "registerNostro"; version = 1; hex = "5a8f3fca4788ec185dba32b55aac0d4af973abd8cd09fea390e5f7e0a36c3a0c" },
      { family = "captureDeal"; version = 1; hex = "165fa7d2b3d55ed70e5dc2dc0d56f621e2f61d6cc6c64eced76af528c8a71bb5" },
      { family = "confirmDeal"; version = 1; hex = "34f367e6170a003062be8fc2bf84bd5b6cb1e8eace958cab35344a214875075c" },
      { family = "amendDeal"; version = 1; hex = "1208eb97856dc0effadd735c5e1de7450f6c7bc9405d0d3bc6e10a323850d375" },
      { family = "cancelDeal"; version = 1; hex = "45174cea6ac38af58a6ffeec8b6ec722e95b28cbe5b11fcd85ed1383fbfdf169" },
      { family = "settleDealLeg"; version = 1; hex = "692f68a881dc57acabaee5736916a711c4bf24a689e8612011933a372260b5e8" },
      { family = "markDeal"; version = 1; hex = "045a6fb6fd34efbf8ffd585c4cf0152f4d3fdc65d3a4d2e7d0f6f79a5e518e01" },
      { family = "recordNostroStatement"; version = 1; hex = "fcc36050e61df53e1bd9992c7724e401d6994d54943a02b087c6cf548f9160e1" },
      { family = "resolveNostroBreak"; version = 1; hex = "1e9b0d9c7cea3017e0e2d05e0e5e677fe521d6302f89974c681b35cd3d091522" },
    ]
  };
}
