#!/usr/bin/env python3
"""gen_feed_vectors.py: the feed's signature vectors for the Motoko battery: a deterministic ML-DSA-44 key from the
reference tool (tools/pq/mldsa44-ref), one figure signed over the desk's canonical message under the feed's context,
written to test/support/FeedVectors.mo. The desk verifies; this side signs."""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TOOL = os.path.join(HERE, "pq", "mldsa44-ref", "mldsa44_tool")
CONTEXT = "thebes.desk.feed.v1"


def canonical_text(t):
    b = t.encode()
    return len(b).to_bytes(2, "big") + b


def canonical_nat(n):
    if n == 0:
        return b"\x00"
    b = n.to_bytes((n.bit_length() + 7) // 8, "big")
    return bytes([len(b)]) + b


def feed_message(isin, source, price_micro, as_of):
    return canonical_text("THEBES-FEED-PRICE-v1") + canonical_text(isin) + canonical_text(source) + canonical_nat(price_micro) + canonical_nat(as_of)


def keygen(seed_hex):
    out = subprocess.run([TOOL, "keygen", seed_hex], capture_output=True, text=True, check=True).stdout.split()
    return bytes.fromhex(out[0]), out[1]


def sign(sk_hex, message, workdir):
    path = os.path.join(workdir, "msg.bin")
    open(path, "wb").write(message)
    return bytes.fromhex(subprocess.run([TOOL, "sign", sk_hex, CONTEXT, path], capture_output=True, text=True, check=True).stdout.strip())


def mo_blob(b):
    return '"' + "".join(f"\\{x:02x}" for x in b) + '" : Blob'


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "..", "test", "support", "FeedVectors.mo")
    import tempfile
    pk, sk = keygen("a1" * 32)
    isin, source, price, as_of = "EG0000012345", "BLOOMBERG", 98_450_000, 1_781_000_000_000_000_000
    with tempfile.TemporaryDirectory() as d:
        sig = sign(sk, feed_message(isin, source, price, as_of), d)
    body = f'''/// FeedVectors.mo: generated by tools/gen_feed_vectors.py from the ML-DSA-44 reference tool; a figure signed over the
/// desk's canonical feed message under the feed's context. Regenerate with the tool; never edit by hand.
module {{
  public let isin : Text = "{isin}";
  public let source : Text = "{source}";
  public let priceMicro : Nat = {price};
  public let asOf : Nat64 = {as_of};
  public let publicKey : Blob = {mo_blob(pk)};
  public let signature : Blob = {mo_blob(sig)};
}}
'''
    open(out, "w").write(body)
    print(f"wrote {out}: pk {len(pk)} bytes, signature {len(sig)} bytes")
