/// record_command_vectors.mo: prints `test/CommandVectors.mo`, the hash of every command sample under every encoding
/// version this build offers. Run through tools/record_command_vectors.sh when a family is added; never when a
/// family's bytes change, which is a new version with the old encoder kept.
///
/// Attribution: Thebes Core Team. Licence: Apache 2.0.

import Debug "mo:core/Debug";
import Nat8 "mo:core/Nat8";

import Freeze "mo:kernel/domain/Freeze";
import Can "../src/DeskCanonical";
import S "../test/support/CommandSamples";

Debug.print("/// CommandVectors.mo: the recorded hash of every command family under every encoding version. Generated by");
Debug.print("/// tools/record_command_vectors.sh; a hash that moves under a version that shipped is a build failure.");
Debug.print("///");
Debug.print("/// Attribution: Thebes Core Team. Licence: Apache 2.0.");
Debug.print("");
Debug.print("import Freeze \"mo:kernel/domain/Freeze\";");
Debug.print("");
Debug.print("module {");
Debug.print("  public func vectors() : [Freeze.Vector] {");
Debug.print("    [");
for (v in Freeze.recordAll(Can.registry(), S.samples()).vals()) {
  Debug.print("      { family = \"" # v.family # "\"; version = " # Nat8.toText(v.version) # "; hex = \"" # v.hex # "\" },");
};
Debug.print("    ]");
Debug.print("  };");
Debug.print("}");
